trigger:
  branches: { include: [ main ] }
  paths:    { include: [ API/PSGalleryStatsReader/** ] }

pr:
  branches: { include: [ main ] }
  paths:    { include: [ API/PSGalleryStatsReader/** ] }

pool: { vmImage: 'ubuntu-latest' }

steps:
- checkout: self
  fetchDepth: 0

- task: ArchiveFiles@2
  displayName: Pack PSGalleryStatsReader
  inputs:
    rootFolderOrFile: 'API/PSGalleryStatsReader'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(PACKAGE)'
    replaceExistingArchive: true
    verbose: false

- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Andys Azure Subscription(6e606d01-ff42-4cab-bcf2-b8888ab2fdc4)'
    appType: 'functionApp'
    appName: 'PSGalleryStatsReader'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
